version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./postgres_data/db:/var/lib/postgres/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    environment:
      - "DJANGO_SECRET_KEY=QHru7iatgbBPxFzxZKg3QNHFunoCUy-7v43WpM3vwN8fnvNsQ3k"
      - "DJANGO_DEBUG=TRUE"

    depends_on:
      - db
